
services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - upload_data:/uploads

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - api
      
volumes:
  upload_data:
